export const LOGIN_GUEST = 'LOGIN_GUEST';
export const LOGIN_SUCEEDED = 'LOGIN_SUCEEDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const SIGNUP_SUCEEDED = 'SIGNUP_SUCEEDED';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
